### Analisando os dados do 156, traga os bairros que tiveram problema com morcegos

SELECT 
	
   DISTINCT BAIRRO_ASS
    
FROM chamados156  

WHERE SUBDIVISAO > 'Morcegos'

### Resposta: CENTRO CIVICO	,CASCATINHA	,GUAIRA	,SITIO CERCADO	,CENTRO	,XAXIM	,MERCES	,SAO JOAO	,PINHEIRINHO	,JARDIM , AMERICAS	,BOM RETIRO	,RIVIERA	,CIDADE INDUSTRIAL	,BOQUEIRAO	,JUVEVE	,SAO BRAZ	,BAIRRO ALTO	,CAMPINA DO SIQUEIRA	,FANNY	,ALTO DA RUA XV	,CAJURU	,CAMPO COMPRIDO	,PAROLIN	,SANTA FELICIDADE	,VISTA ALEGRE
